version: '3.1'

services:
  bodova3:
    build: 
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - "eshop"

  eshop:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: eshop
    expose:
      - 3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "eshop"
    environment:
      ADMINER_DEFAULT_SERVER: eshop